---
title: "Data Exploration"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(multcomp)
library(plotly)
library(leaflet)
library(ggplot2)
library(lubridate)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = T,
  echo = T,
  warning = T,
  cache = F
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)

scale_colour_discrete = scale_colour_viridis_d

scale_fill_discrete = scale_fill_viridis_d

```

# Load data
```{r load_data}
cafe = read_csv(here::here("data/Sidewalk_Caf__Licenses_and_Applications_clean.csv"))

parking = read_csv(
  here::here("data/parking_vio2021_cleanv1.csv"))

```

# Cafe Map
```{r cafe_map}
plot_cafe_map =
  parking %>%
  count(street_name, name = "ticket") %>%
  right_join(cafe) %>%
  mutate(ticket = replace_na(ticket,1e-10))

pal = colorNumeric(palette = c("viridis", "magma", "inferno","plasma")[[4]],
                   domain = plot_cafe_map$ticket %>% log())

plot_cafe_map =
  plot_cafe_map%>%
  mutate(pop =
           str_c("<b>",business_name,"</b><br>",round(ticket)," tickets")) %>% 
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(
    ~ long,
    ~ lat,
    color = ~pal(ticket %>% log()),
    radius = .1,
    popup = ~ (pop)
  )

plot_cafe_map
```

## plot violation vs time

convert date and format

```{r}
parking_time = 
  parking %>% 
  select(issue_date,summons_number, vehicle_make, hour, min) %>% 
  separate(issue_date, into = c('month', 'day', 'year'), sep = '/') %>% 
  mutate( month = as.numeric(month)) %>% 
  select(-year) 
  

    
```

Make line plots: violation vs month

```{r}
parking_time %>% 
  group_by(month) %>% 
  summarize(n = n()) %>%
  plot_ly(x = ~month, y =~n, type = 'scatter',mode = 'line')%>%
  layout(
    title = 'Violations per Month',
    xaxis = list(
      type = 'category',
      title = 'Month'),
    yaxis = list(
      title = 'Count of violations'))
```

plots: violation vs weekday
```{r}
library(readr)
parking_day = read_csv("data/parking_vio2021_cleanv1.csv", 
    col_types = cols(issue_date = col_date(format = "%m/%d/%Y"))) %>%
  select(issue_date, summons_number)

parking_day %>% 
  mutate(issue_date = as_date(issue_date))%>%
  mutate(day_week = weekdays(issue_date))%>%
  mutate(day_week = fct_relevel(day_week, levels = c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'))) %>%
  group_by(day_week) %>% 
  summarize(n = n()) %>%
  plot_ly(x = ~day_week, y =~n, type = 'scatter',mode = 'line')%>%
  layout(
    title = 'Violations by weekday',
    xaxis = list(
      type = 'category',
      title = 'Weekday'),
    yaxis = list(
      title = 'Count of violations'))
```


Line plots: vilation vs hour
```{r}
parking_time %>% 
  group_by(hour) %>% 
  summarize(n = n()) %>%
  filter(hour != 12.3) %>% 
  plot_ly(x = ~hour, y = ~n, type = 'scatter',mode = 'line') %>%
  layout(
    title = 'Violations per Hour',
    xaxis = list(
      type = 'category',
      title = 'Hour',
      range = c(0, 23)),
    yaxis = list(
      title = 'Count of violations'))
```



##violation type

```{r}

vio_code = readxl::read_xlsx('data/ParkingViolationCodes_January2020.xlsx') %>% 
  janitor::clean_names() %>% 
  select(violation_code, violation_description) %>% 
  mutate(violation_description = str_to_lower(violation_description))

violation_count = 
  parking %>% 
  group_by(violation_code) %>% 
  summarise(n = n()) %>% 
  left_join(vio_code, by = 'violation_code') %>% 
  arrange(desc(n)) %>% 
  filter(n > 10000)
```

bar_plot

```{r}
violation_count %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis")
```


##violation type by Borough

```{r}

vio_count_boro = 
  parking %>% 
  left_join(vio_code, by = 'violation_code') %>% 
  drop_na()



Manhattan_vio = 
  vio_count_boro %>% 
  filter(borough == 'Manhattan') %>% 
  group_by(violation_code, violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  head(10) %>% 
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(
    title = 'Top 10 violations in Manhattan',
    xaxis = list(
      type = 'category',
      title = 'violation description'),
    yaxis = list(
      title = 'Count of violations'))



Queens_vio = 
  vio_count_boro %>% 
  filter(borough == 'Queens') %>% 
  group_by(violation_code, violation_description) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(
    title = 'Top 10 violations in Queens',
    xaxis = list(
      type = 'category',
      title = 'violation description'),
    yaxis = list(
      title = 'Count of violations'))

Bronx_vio = 
  vio_count_boro %>% 
  filter(borough == 'Bronx') %>% 
  group_by(violation_code, violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  head(10) %>% 
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(
    title = 'Top 10 violations in Bronx',
    xaxis = list(
      type = 'category',
      title = 'violation description'),
    yaxis = list(
      title = 'Count of violations'))

Brooklyn_vio = 
  vio_count_boro %>% 
  filter(borough == 'Brooklyn') %>% 
  group_by(violation_code, violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  head(10) %>% 
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(
    title = 'Top 10 violations in Brooklyn',
    xaxis = list(
      type = 'category',
      title = 'violation description'),
    yaxis = list(
      title = 'Count of violations'))

Staten_vio = 
  vio_count_boro %>% 
  filter(borough == 'Staren Iland') %>% 
  group_by(violation_code, violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  head(10) %>% 
  plot_ly(x = ~violation_description, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(
    title = 'Top 10 violations in Staten Island',
    xaxis = list(
      type = 'category',
      title = 'violation description'),
    yaxis = list(
      title = 'Count of violations'))
  
Manhattan_vio
Queens_vio
Bronx_vio
Brooklyn_vio
Staten_vio
```


