---
title: "Violation Types"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, echo=FALSE, include = FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(plotly)
library(leaflet)
library(ggplot2)
library(lubridate)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = T,
  echo = T,
  warning = T,
  cache = F
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)

scale_colour_discrete = scale_colour_viridis_d

scale_fill_discrete = scale_fill_viridis_d

```


```{r, echo = FALSE, message=FALSE,warning = FALSE}
parking = read_csv(
  here::here("data/parking_vio2021_cleanv1.csv")) %>% 
  filter(hour != 12.3) 
```




```{r, echo = FALSE, message=FALSE,warning = FALSE}
vio_code = readxl::read_xlsx('data/ParkingViolationCodes_January2020.xlsx') %>% 
  janitor::clean_names() %>% 
  dplyr::select(violation_code, violation_description) %>% 
  mutate(violation_description = str_to_lower(violation_description))

vio_count_boro = 
  parking %>% 
  left_join(vio_code, by = 'violation_code')

violation_count = 
  parking %>% 
  group_by(violation_code) %>% 
  summarise(n = n()) %>% 
  left_join(vio_code, by = 'violation_code') %>% 
  arrange(desc(n)) %>% 
  filter(n > 10000)


```


<h3><center>Over View of Tickets Type generated in Year 2021</center></h3>

Overall, there are 79 different types of violation happened in NYC. The most freqently violated are 'photo school zone spped violation', 'street cleaning parking violation', 'fail to display meter receipt', and offedning 'no-parking-day-time limits'.


```{r,echo = FALSE, message=FALSE,warning = FALSE}
violation_count %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") +
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "none"
  ) 
  
```


<h3><center>Top 10 violation types in each borough</center></h3>

```{r, echo = FALSE, message=FALSE,warning = FALSE}


Manhattan_vio = 
  vio_count_boro %>% 
  filter(borough == 'Manhattan') %>% 
  group_by(violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  ) +
  labs(
    title = 'Top 10 violations in Manhattan') +
    xlab("violation description") +
    ylab('Count of tickets')  



Queens_vio = 
  vio_count_boro %>% 
  filter(borough == 'Queens') %>% 
  group_by(violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  ) +
  labs(
    title = 'Top 10 violations in Queens') +
    xlab("violation description") +
    ylab('Count of tickets') 


Bronx_vio = 
  vio_count_boro %>% 
  filter(borough == 'Bronx') %>% 
  group_by(violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  ) +
  labs(
    title = 'Top 10 violations in Bronx') +
    xlab("violation description") +
    ylab('Count of tickets')  


Brooklyn_vio = 
  vio_count_boro %>% 
  filter(borough == 'Brooklyn') %>% 
  group_by(violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  ) +
  labs(
    title = 'Top 10 violations in Brooklyn') +
    xlab("violation description") +
    ylab('Count of tickets') 



Staten_vio = 
  vio_count_boro %>% 
  filter(borough == 'Staten Island') %>% 
  group_by(violation_description) %>% 
  summarize(n = n()) %>% 
  mutate(violation_description = fct_reorder(violation_description, n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = violation_description, y = n, fill = violation_description)) +
  geom_bar(stat = "identity") + 
  theme(
    axis.text.x = element_text(angle = 90, vjust = .5, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  ) +
  labs(
    title = 'Top 10 violations in Staten Island') +
    xlab("violation description") +
    ylab('Count of tickets')  


  
Manhattan_vio
Queens_vio 
Bronx_vio
Brooklyn_vio
Staten_vio


```


<b>A small finding</b>: According to the distribution of vehicle makes of the violation tickets dataset, we can roughly know the tops 10 vehicle make that are most popular among new yorkers.

```{r,echo = FALSE, message=FALSE,warning = FALSE}
parking %>% 
  select(id, vehicle_make) %>% 
  group_by(vehicle_make) %>% 
  summarise(n = n()) %>% 
  filter(n>10) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  mutate(vehicle_make = fct_reorder(vehicle_make, n)) %>% 
  plot_ly(x = ~vehicle_make, y = ~n, type = "bar", colors = "viridis")
```

